### ISSUE TITLE
Char `:`not accepted in the field name of the config if a macros is in it.

### ISSUE THREAD

**Issue by agaget** [epics-extensions/WeTest#87]
```
config:
    type: "unit"
    name: " ${DEST} : BDM scenario destination OK "  # <------------------- this line
    prefix: "SL-MPS-BDM:MPS-EVR-01:"
    delay: 1.5
```
Got the following message

```
Schema validation failed:
 - Value '{'EIS.BB': 'BDM scenario destination OK'}' is not of type 'str'. Path: '/config/name'.
Mandatory validation failed:
 - `name` in `config` is supposed to be a string but got: {'EIS.BB': 'BDM scenario destination OK'}
```

If I remove the macro DEST or the `:` it doesn't failed.
So the following works well :
`
    name: " EIS BB : BDM scenario destination OK "
`

`
    name: " $(DEST) - BDM scenario destination OK "
`
