### ISSUE TITLE
Possibility to add On failure more easily

### ISSUE THREAD

**Issue by agaget** [epics-extensions/WeTest#88]
On the following example, if I want to add **on_failure** to `pause` I need to add it to each individual file test. That is heavy. It would be interesting to set it up more easily.

Or to have it in option:` wetest main.yal --on_failure=pause`

```
version:
    major: 2
    minor: 0
    bugfix: 0

name: "BOM sequence"
on_failure: "pause"

include:
    - ['bom_scenario1.yaml']
    - ['bom_scenario2.yaml']
    # # need stop beam, I don't know how to do it for now
    - ['bom_scenario3.yaml'] # x
    - ['bom_scenario4.yaml']
    - ['bom_scenario5.yaml']
    - ['bom_scenario6.yaml'] # x
```
