### ISSUE TITLE
When setting a string value into to a waveform-of-char PV, a "b" char is appended

### ISSUE THREAD

**Issue by gabriel-desmarchelier** [epics-extensions/WeTest#92]
When setting a string value into to a waveform-of-char PV, a "b" char is appended

Steps to reproduce :

EPICS record :
```
# String to write in
record(waveform, "Test:TextOut") {
    field(NELM, "32")
    field(FTVL, "CHAR")
}
```

WeTest file :
```
version:
    major: 2
    minor: 0
    bugfix: 0

config:
    type: "unit"
    name: "Writing text PV"
    delay: 0.5

tests:
    - name: "Writing text PV"
      commands:
          - name: "Writing text PV"
            setter: "Test:TextOut"
            set_value: "myText"
          - name: "Reading text PV"
            getter: "Test:TextOut"
            get_value: "myText"
```

WeTest result :
```
Ready to start testing, use GUI play button.
Applying selection may take some time.

Running    test-0-0-0    Writing text PV: Writing text PV
Success of test-0-0-0    (in 0.531s) 

Running    test-0-0-1    Writing text PV: Reading text PV
Failure of test-0-0-1    (in 0.502s) Expected Test:TextOut to be `myText`, but got `myTextb`
```
